fluxbase Class Reference
Class Fluxbase.
#include <flux.h>
Public Member Functions
virtual double eval (double *, double *, double *, double *, double *)=0
Virtual evaluation of the flux.
virtual void eval_l (double *, double *, double *, double *, double *)=0
Virtual non conservative evaluation of the flux on the left of the element.
virtual void eval_r (double *, double *, double *, double *, double *)=0
Virtual non conservative evaluation of the flux on the right of the element.
Detailed Description
Class Fluxbase.
Member Function Documentation
virtual double fluxbase::eval (double * , double * , double * , double * , double *) [pure virtual]
Virtual evaluation of the flux.
Implemented in lfgrassmomentumdiffusion , suspendedsediment , grassburgers , lfgrassmomentum , lfgrass , hllgrass , sedimenttransport , swehllctopography , swehllc , burgersdiffusion , burgers , and advection .
Referenced by fluxproc().
virtual void fluxbase::eval_l (double * , double * , double * , double * , double *) [pure virtual]
Virtual non conservative evaluation of the flux on the left of the element.
Implemented in lfgrassmomentumdiffusion , suspendedsediment , grassburgers , lfgrassmomentum , lfgrass , hllgrass , sedimenttransport , swehllctopography , swehllc , burgersdiffusion , burgers , and advection .
Referenced by fluxproc().
virtual void fluxbase::eval_r (double * , double * , double * , double * , double *) [pure virtual]
Virtual non conservative evaluation of the flux on the right of the element.
Implemented in lfgrassmomentumdiffusion , suspendedsediment , grassburgers , lfgrassmomentum , lfgrass , hllgrass , sedimenttransport , swehllctopography , swehllc , burgersdiffusion , burgers , and advection .
Referenced by fluxproc().
The documentation for this class was generated from the following file:
flux.h