eulerforw.cpp File Reference
#include <vector>
*
#include <iostream>
*
#include `node.h`
*
#include `state.h`
*
#include `element.h`
*
#include `source.h`
*
#include `flux.h`
*
#include `flux2.h`
*
#include `fluxproc.h`
*
#include `flux2proc.h`
*
#include `sourceproc.h`
*
#include `eulerforw.h`
*
#include `updatenodes.h`
*
Functions
int eulerforw (double &dt, vector< node > &Nodes, vector< element > &Elements, int bcl, int bcr, testtypedescr testtype, fluxbase *fluxtype, sourcebase *sourcetype, flux2base *flux2type, double t)
Euler Forward Time Integration.
Function Documentation
int eulerforw (double & dt, vector< node > & Nodes, vector< element > & Elements, int bcl, int bcr, testtypedescr testtype, fluxbase * fluxtype, sourcebase * sourcetype, flux2base * flux2type, double t)
Euler Forward Time Integration.
References flux2proc(), fluxproc(), sourceproc(), state::statesize, element::systemsize1, and element::systemsize2.
Referenced by main().