exactriemann.cpp File Reference
#include <vector>
*
#include <math.h>
*
#include `physpara.h`
*
Functions
double Function1 (double hk, double h, int n)
double Function2 (double hk, double h, int n)
double exactriemann (double hl, double ml, double hr, double mr, double xs, double x, double t, int j)
Solution of Riemann Problem for Shallow Water Equations by Vijaya Raghav Ambati.
Function Documentation
double exactriemann (double hl, double ml, double hr, double mr, double xs, double x, double t, int j)
Solution of Riemann Problem for Shallow Water Equations by Vijaya Raghav Ambati.
References Function1(), Function2(), and gravity_const.
Referenced by testfcn().
double Function1 (double hk, double h, int n)
References gravity_const.
Referenced by exactriemann().
double Function2 (double hk, double h, int n)
References gravity_const.
Referenced by exactriemann().