exactriemann.h File Reference
Functions
double exactriemann (double hl, double ul, double hr, double ur, double xs, double x, double t, int j)
Solution of Riemann Problem for Shallow Water Equations by Vijaya Raghav Ambati.
Function Documentation
double exactriemann (double hl, double ul, double hr, double ur, double xs, double x, double t, int j)
Solution of Riemann Problem for Shallow Water Equations by Vijaya Raghav Ambati.
References Function1(), Function2(), and gravity_const.
Referenced by testfcn().