flux2proc.cpp File Reference
#include <vector>
*
#include <iostream>
*
#include <math.h>
*
#include `state.h`
*
#include `element.h`
*
#include `node.h`
*
#include `flux2.h`
*
#include `enumtypes.h`
*
#include `flux2proc.h`
*
#include `updatenodes.h`
*
Functions
int flux2proc (vector< node > &Nodes, vector< element > &Elements, int bcl, int bcr, testtypedescr testtype, flux2base *flux2type, double t)
Function Documentation
int flux2proc (vector< node > & Nodes, vector< element > & Elements, int bcl, int bcr, testtypedescr testtype, flux2base * flux2type, double t)
References flux2base::eval(), state::statesize, element::systemsize1, element::systemsize2, and updatenodesu().
Referenced by cranknicolsonwp(), eulerforw(), and rk3().