fluxproc.cpp File Reference
#include <vector>
*
#include <iostream>
*
#include <cmath>
*
#include `state.h`
*
#include `element.h`
*
#include `node.h`
*
#include `flux.h`
*
#include `fluxproc.h`
*
#include `enumtypes.h`
*
#include `updatenodes.h`
*
#include `physpara.h`
*
Functions
int fluxproc (vector< node > &Nodes, vector< element > &Elements, int bcl, int bcr, testtypedescr testtype, fluxbase *fluxtype, double t)
Function Documentation
int fluxproc (vector< node > & Nodes, vector< element > & Elements, int bcl, int bcr, testtypedescr testtype, fluxbase * fluxtype, double t)
References dissipation_alpha, dissipation_beta, dissipation_const, fluxbase::eval(), fluxbase::eval_l(), fluxbase::eval_r(), state::statesize, element::systemsize1, and updatenodesq().
Referenced by cranknicolsonwp(), eulerforw(), and rk3().