plotting.m File Reference
Functions
fscanf (fid,'%u',[1 1])
It has two rows now fclose (fid)
It has two rows now a (2,:)
figure (1)%plot(b(1
b (2,:)
b_new (2,(ii-1)*gg+(jj)*2+1)
end b_new (2,(ii-1)*gg+2 *gg)
plot (a(1,(jj-1)*Nn+1:jj *Nn), a(2,(jj-1)*Nn+1:jj *Nn),'g-')
subplot (M1, 1, jj) plot(b(1
plot (a(1,(jj+M1a-1)*Nn+1:(jj+M1a)*Nn), a(2,(jj+M1a-1)*Nn+1:(jj+M1a)*Nn),'g-')
Variables
clear
fid = fopen('init.160')
Ma =fscanf(fid,'%u',[2 1])
M1a = Ma(1)
M2a = Ma(2)
Nn = fscanf(fid,'%u',[1 1])
a = fscanf(fid,'%g %g',[2 inf])
ext = [160]
for kk
Mb =fscanf(fid,'%u',[2 1])
M1b = Mb(1)
M2b = Mb(2)
Nnb = fscanf(fid,'%u',[1 1])
clear b = fscanf(fid,'%g %g',[2 inf])
B needs to be extended to the
*
same length as a gg = Nn/Nnb
b_new = a
__pad0__
for ii
for jj
hold on
hold off
Function Documentation
It has two rows now a (2 , :)
b (2 , :)
b_new (2 , (ii-1)*gg+(jj)*2+ 1)
end b_new (2 , (ii-1)*gg+2 * gg)
It has two rows now fclose (fid)
figure (1)
fscanf (fid , '%u')
plot (a(1,(jj-1)*Nn+1:jj *Nn) , a(2,(jj-1)*Nn+1:jj *Nn) , 'g-')
plot (a(1,(jj+M1a-1)*Nn+1:(jj+M1a)*Nn) , a(2,(jj+M1a-1)*Nn+1:(jj+M1a)*Nn) , 'g-')
subplot (M1 , 1 , jj)
Variable Documentation
__pad0__
a = fscanf(fid,'%g %g',[2 inf])
Referenced by advection::eval(), initcon(), and readmesh().
end b = fscanf(fid,'%g %g',[2 inf])
Referenced by initcon().
b_new = a
clear
ext = [160]
Referenced by main().
fid = fopen('init.160')
B needs to be extended to the same length as a gg = Nn/Nnb
for ii
Initial value:
= 1:2:Nnb
        b_new(2, (ii-1)*gg+1) = b(2,ii)
end for jj
Initial value:
= 1:gg-1
            b_new(2, (ii-1)*gg+(jj)*2) = (b(2,ii)*(gg-jj)+b(2,ii+1)*jj)/(gg)
for kk
Initial value:
= 1:length(ext)
    fid = fopen(['out.',int2str(ext(kk))])
M1a = Ma(1)
M1b = Mb(1)
M2a = Ma(2)
M2b = Mb(2)
Ma =fscanf(fid,'%u',[2 1])
Mb =fscanf(fid,'%u',[2 1])
Nn = fscanf(fid,'%u',[1 1])
Referenced by readmesh().
Nnb = fscanf(fid,'%u',[1 1])
hold off
hold on