readtest.h File Reference
#include <string>
*
#include `enumtypes.h`
*
Functions
int readtest (testtypedescr &testtype, timeintmethod &timeint, string &meshname, double &CFL, double &it, double &et, int &deg)
Function for reading the test.
int writetest (testtypedescr &testtype, timeintmethod &timeint, string &meshname, double &CFL, double &it, double &et, int &deg)
Function for writing the test (not used any longer).
int readtest2 (testtypedescr &testtype, timeintmethod &timeint, string &meshname, double &CFL, double &it, double &et, int &deg, string testname)
Function for reading the test with filename.
Function Documentation
int readtest (testtypedescr & testtype, timeintmethod & timeint, string & meshname, double & CFL, double & it, double & et, int & deg)
Function for reading the test.
References readtest2(), and writetest().
int readtest2 (testtypedescr & testtype, timeintmethod & timeint, string & meshname, double & CFL, double & it, double & et, int & deg, string testname)
Function for reading the test with filename.
References Advection, Burgers, BurgersDiffusive, CrankNicolsonWithPredictor, DecoupledGrassSedimentOnly, EulerForward, HLLGrass, LFGrass, LFGrassMomentum, LFGrassMomentumDiffusion, RungeKutta3, SedimentTransport, SuspendedSediment, SWEBurgers, SWEContinuousTopography, SWEDiscontinuousTopography, SWEFlowOverIsolatedContinuousRidgeI, SWEFlowOverIsolatedContinuousRidgeIV, SWEFlowOverIsolatedDiscontinuousRidgeI, SWEFlowOverIsolatedDiscontinuousRidgeIV, SWEFlowOverSinyBedI, SWELinearWaveSolution, SWERiemannProblemLeftRarefactionRightRarefaction, SWERiemannProblemLeftRarefactionRightShock, SWERiemannProblemLeftShockRightRarefaction, and SWERiemannProblemLeftShockRightShock.
Referenced by main(), and readtest().
int writetest (testtypedescr & testtype, timeintmethod & timeint, string & meshname, double & CFL, double & it, double & et, int & deg)
Function for writing the test (not used any longer).
Referenced by readtest().