sourceproc.h File Reference
#include `state.h`
*
#include `element.h`
*
#include `node.h`
*
Functions
int sourceproc (vector< node > Nodes, vector< element > &Elements, sourcebase *sourcetype)
Function which calculates the source for the complete system.
Function Documentation
int sourceproc (vector< node > Nodes, vector< element > & Elements, sourcebase * sourcetype)
Function which calculates the source for the complete system.
References element::ep, sourcebase::eval(), state::statesize, and element::systemsize1.
Referenced by cranknicolsonwp(), eulerforw(), and rk3().