st_1ddg.cpp File Reference
#include <iostream>
*
#include <fstream>
*
#include <cmath>
*
#include <vector>
*
#include `node.h`
*
#include `state.h`
*
#include `element.h`
*
#include `flux.h`
*
#include `source.h`
*
#include `flux2.h`
*
#include `enumtypes.h`
*
#include `readtest.h`
*
#include `readmesh.h`
*
#include `physpara.h`
*
#include `initcon.h`
*
#include `output.h`
*
#include `flux2proc.h`
*
#include `eulerforw.h`
*
#include `rk3.h`
*
#include `cranknicolsonwp.h`
*
#include `updatenodes.h`
*
Functions
string itoa (int i)
double getdt (vector< element > Elements, testtypedescr testtype)
int main (int argc, char *argv[])
Function Documentation
double getdt (vector< element > Elements, testtypedescr testtype)
References Advection, advection_speed, Burgers, BurgersDiffusive, Grass_const, gravity_const, HLLGrass, LFGrass, SedimentTransport, SWEBurgers, SWEContinuousTopography, SWEDiscontinuousTopography, SWEFlowOverIsolatedContinuousRidgeI, SWEFlowOverIsolatedContinuousRidgeIV, SWEFlowOverIsolatedDiscontinuousRidgeI, SWEFlowOverIsolatedDiscontinuousRidgeIV, SWEFlowOverSinyBedI, SWELinearWaveSolution, SWERiemannProblemLeftRarefactionRightRarefaction, SWERiemannProblemLeftRarefactionRightShock, SWERiemannProblemLeftShockRightRarefaction, and SWERiemannProblemLeftShockRightShock.
Referenced by main().
string itoa (int i)
Referenced by main().
int main (int argc, char * argv[])
References Advection, Burgers, BurgersDiffusive, element::CFL, CrankNicolsonWithPredictor, cranknicolsonwp(), DecoupledGrassSedimentOnly, eulerforw(), EulerForward, ext, getdt(), HLLGrass, initcon(), itoa(), LFGrass, LFGrassMomentum, LFGrassMomentumDiffusion, output(), readmesh(), readtest2(), rk3(), RungeKutta3, SedimentTransport, state::statesize, SuspendedSediment, SWEBurgers, SWEContinuousTopography, SWEDiscontinuousTopography, SWEFlowOverIsolatedContinuousRidgeI, SWEFlowOverIsolatedContinuousRidgeIV, SWEFlowOverIsolatedDiscontinuousRidgeI, SWEFlowOverIsolatedDiscontinuousRidgeIV, SWEFlowOverSinyBedI, SWELinearWaveSolution, SWERiemannProblemLeftRarefactionRightRarefaction, SWERiemannProblemLeftRarefactionRightShock, SWERiemannProblemLeftShockRightRarefaction, SWERiemannProblemLeftShockRightShock, element::systemsize1, and element::systemsize2.