testfcn.h File Reference
#include `enumtypes.h`
*
Functions
double testfcn (testtypedescr testtype, int j, double x)
double testfcn (testtypedescr testtype, int j, double x, double t)
Function Documentation
double testfcn (testtypedescr testtype, int j, double x)
References testfcn().
Referenced by initcon(), testfcn(), updatenodesq(), and updatenodesu().
double testfcn (testtypedescr testtype, int j, double x, double t)
References Advection, Burgers, BurgersDiffusive, DecoupledGrassSedimentOnly, exactriemann(), gravity_const, HLLGrass, LFGrass, LFGrassMomentum, LFGrassMomentumDiffusion, SedimentTransport, SuspendedSediment, SWEBurgers, SWEContinuousTopography, SWEDiscontinuousTopography, SWEFlowOverIsolatedContinuousRidgeI, SWEFlowOverIsolatedContinuousRidgeIV, SWEFlowOverIsolatedDiscontinuousRidgeI, SWEFlowOverIsolatedDiscontinuousRidgeIV, SWEFlowOverSinyBedI, SWELinearWaveSolution, SWERiemannProblemLeftRarefactionRightRarefaction, SWERiemannProblemLeftRarefactionRightShock, SWERiemannProblemLeftShockRightRarefaction, SWERiemannProblemLeftShockRightShock, and testfcn().