updatenodes.cpp File Reference
#include <vector>
*
#include <iostream>
*
#include <math.h>
*
#include <stdlib.h>
*
#include `state.h`
*
#include `element.h`
*
#include `node.h`
*
#include `flux.h`
*
#include `testfcn.h`
*
#include `updatenodes.h`
*
#include `enumtypes.h`
*
Functions
int updatenodesu (vector< node > &Nodes, vector< element > &Elements, int bcl, int bcr, testtypedescr testtype, double t)
int updatenodesq (vector< node > &Nodes, vector< element > &Elements, int bcl, int bcr, testtypedescr testtype, double t)
Function Documentation
int updatenodesq (vector< node > & Nodes, vector< element > & Elements, int bcl, int bcr, testtypedescr testtype, double t)
References SWEFlowOverSinyBedI, element::systemsize2, and testfcn().
Referenced by fluxproc().
int updatenodesu (vector< node > & Nodes, vector< element > & Elements, int bcl, int bcr, testtypedescr testtype, double t)
Update interpolation points in the Element.
References element::systemsize1, and testfcn().
Referenced by flux2proc().